### ISSUE TITLE
Send email after creating or modifying a tunnel

### ISSUE THREAD

**Issue by invliD** [invliD/lana-dashboard#12]
Send an email to the other party (if it's not the same institution) on creation and modification.

**Comment by kaifabian** [comment]
I would recommend to making this an optional feature, e. g. as it is implemented on BillsUp.com ("Save and notify" / "Save but do not notify"), so that you don't get mails for every minor change. Whoever edits a tunnel should know whether the change is significant enough to trigger a message or not.

Furthermore, to which email address should these emails be sent? IMHO this should _not_ use the abuse e-mail address. Will you add another "notification e-mail address" field to institutions?

**Comment by invliD** [comment]
@mswart's and my idea was to take both institution's managers in a set and remove the current user. Thus, we don't use the abuse address, but every manager of both institutions (except for the user triggering the change) will get that email.
In addition, every user gets the option to disable these notifications in their profile settings.
Do you think disabling the sending is still necessary?

**Comment by kaifabian** [comment]
At first I thought: We should make sure that we do not send mails on minor changes that require no action on behalf of the manager(s), such as changing the tunnel comment.

But, now that I think about it: the "comment" field would be the only exception since all other tunnel information is relevant, and IMHO it is not worth the effort to handle this one field different from the others (specially since changing the tunnel comment is not something that is done often).

**Comment by invliD** [comment]
Closed in 3b8be71.
