### ISSUE TITLE
Tunnel Type: vtun

### ISSUE THREAD

**Issue by dstelter** [invliD/lana-dashboard#14]
Why u discriminate vtun? :-(

**Comment by kaifabian** [comment]
![image](http://img.memecdn.com/grumpy-cat-on-discrimination_o_1211102.jpg)
[source](http://www.memecenter.com/fun/1211102/grumpy-cat-on-discrimination)

**Comment by kaifabian** [comment]
Now I'll try to be serious:
I think vtun poses some problems (as other tunnel types do, such as IPsec with PSK): The symmetric secret. We have, right now, no problems with information disclosure, since the fastd authenticity information are public keys. So first we would need to decide on some kind of access control to that information.

Further, @invliD and I talked about that problem. It is planned to support other tunnel types in the future, but this will require some change in the OOP structure of the project (e. g. for allowing configuration generation for the other tunnel types, allowing different types to have additional fields, ...), so this is not some 5-minute-feature. AFAIK implementing this is planned for some future release (likely @invliD will elaborate on that).
